# Generated by Django 5.1 on 2024-09-07 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="watchagain",
            new_name="watchAgain",
        ),
    ]
