# Generated by Django 5.1 on 2024-09-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=50)),
                ("run", models.IntegerField()),
                ("balls", models.IntegerField()),
                ("s4", models.IntegerField()),
                ("s6", models.IntegerField()),
                ("sr", models.FloatField()),
                ("team", models.CharField(max_length=100)),
                ("opponent", models.CharField(max_length=100)),
            ],
        ),
    ]
